# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaPrincipal(object):
    def setupUi(self, TelaPrincipal):
        TelaPrincipal.setObjectName("TelaPrincipal")
        TelaPrincipal.resize(560, 470)
        TelaPrincipal.setMinimumSize(QtCore.QSize(560, 470))
        TelaPrincipal.setMaximumSize(QtCore.QSize(560, 470))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("designer\\../img/icone.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TelaPrincipal.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(TelaPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(50, 50, 50, 50)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_Local = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Local.sizePolicy().hasHeightForWidth())
        self.comboBox_Local.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox_Local.setFont(font)
        self.comboBox_Local.setStyleSheet("QComboBox {\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5%;\n"
"padding: 5px;\n"
"}\n"
"")
        self.comboBox_Local.setObjectName("comboBox_Local")
        self.comboBox_Local.addItem("")
        self.comboBox_Local.setItemText(0, "")
        self.comboBox_Local.addItem("")
        self.comboBox_Local.addItem("")
        self.comboBox_Local.addItem("")
        self.comboBox_Local.addItem("")
        self.comboBox_Local.addItem("")
        self.comboBox_Local.addItem("")
        self.comboBox_Local.addItem("")
        self.comboBox_Local.addItem("")
        self.comboBox_Local.addItem("")
        self.comboBox_Local.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_Local)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_Container_1 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_Container_1.setFont(font)
        self.lineEdit_Container_1.setStyleSheet("QLineEdit {\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5%;\n"
"padding: 5px;\n"
"}\n"
"")
        self.lineEdit_Container_1.setMaxLength(4)
        self.lineEdit_Container_1.setObjectName("lineEdit_Container_1")
        self.horizontalLayout_2.addWidget(self.lineEdit_Container_1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lineEdit_Container_2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_Container_2.setFont(font)
        self.lineEdit_Container_2.setStyleSheet("QLineEdit {\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5%;\n"
"padding: 5px;\n"
"}\n"
"")
        self.lineEdit_Container_2.setMaxLength(6)
        self.lineEdit_Container_2.setObjectName("lineEdit_Container_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_Container_2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.lineEdit_Container_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Container_3.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_Container_3.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_Container_3.setFont(font)
        self.lineEdit_Container_3.setStyleSheet("QLineEdit {\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5%;\n"
"padding: 5px;\n"
"}\n"
"")
        self.lineEdit_Container_3.setMaxLength(1)
        self.lineEdit_Container_3.setObjectName("lineEdit_Container_3")
        self.horizontalLayout_2.addWidget(self.lineEdit_Container_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_Placa = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_Placa.setFont(font)
        self.lineEdit_Placa.setStyleSheet("QLineEdit {\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5%;\n"
"padding: 5px;\n"
"}\n"
"")
        self.lineEdit_Placa.setMaxLength(7)
        self.lineEdit_Placa.setObjectName("lineEdit_Placa")
        self.horizontalLayout_3.addWidget(self.lineEdit_Placa)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.comboBox_Status = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Status.sizePolicy().hasHeightForWidth())
        self.comboBox_Status.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox_Status.setFont(font)
        self.comboBox_Status.setStyleSheet("QComboBox {\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5%;\n"
"padding: 5px;\n"
"}\n"
"")
        self.comboBox_Status.setObjectName("comboBox_Status")
        self.comboBox_Status.addItem("")
        self.comboBox_Status.setItemText(0, "")
        self.comboBox_Status.addItem("")
        self.comboBox_Status.addItem("")
        self.comboBox_Status.addItem("")
        self.comboBox_Status.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_Status)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.pushButton_Enviar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Enviar.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_Enviar.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Enviar.setFont(font)
        self.pushButton_Enviar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Enviar.setObjectName("pushButton_Enviar")
        self.verticalLayout.addWidget(self.pushButton_Enviar)
        self.label_Informativo = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_Informativo.setFont(font)
        self.label_Informativo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_Informativo.setText("")
        self.label_Informativo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Informativo.setObjectName("label_Informativo")
        self.verticalLayout.addWidget(self.label_Informativo)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        TelaPrincipal.setCentralWidget(self.centralwidget)

        self.retranslateUi(TelaPrincipal)
        QtCore.QMetaObject.connectSlotsByName(TelaPrincipal)

    def retranslateUi(self, TelaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        TelaPrincipal.setWindowTitle(_translate("TelaPrincipal", "InfoViewer"))
        self.label_7.setText(_translate("TelaPrincipal", "Painel Informativo"))
        self.label.setText(_translate("TelaPrincipal", "Local:"))
        self.comboBox_Local.setItemText(1, _translate("TelaPrincipal", "RECEPÇÃO"))
        self.comboBox_Local.setItemText(2, _translate("TelaPrincipal", "NAVE 01"))
        self.comboBox_Local.setItemText(3, _translate("TelaPrincipal", "NAVE 02"))
        self.comboBox_Local.setItemText(4, _translate("TelaPrincipal", "NAVE 03"))
        self.comboBox_Local.setItemText(5, _translate("TelaPrincipal", "NAVE 04"))
        self.comboBox_Local.setItemText(6, _translate("TelaPrincipal", "NAVE 05"))
        self.comboBox_Local.setItemText(7, _translate("TelaPrincipal", "NAVE 06"))
        self.comboBox_Local.setItemText(8, _translate("TelaPrincipal", "NAVE 07"))
        self.comboBox_Local.setItemText(9, _translate("TelaPrincipal", "NAVE 08"))
        self.comboBox_Local.setItemText(10, _translate("TelaPrincipal", "NAVE 09"))
        self.label_2.setText(_translate("TelaPrincipal", "Container:"))
        self.label_5.setText(_translate("TelaPrincipal", "-"))
        self.label_6.setText(_translate("TelaPrincipal", "-"))
        self.label_3.setText(_translate("TelaPrincipal", "Placa:"))
        self.label_4.setText(_translate("TelaPrincipal", "Status:"))
        self.comboBox_Status.setItemText(1, _translate("TelaPrincipal", "Documento disponível"))
        self.comboBox_Status.setItemText(2, _translate("TelaPrincipal", "Carregar"))
        self.comboBox_Status.setItemText(3, _translate("TelaPrincipal", "Carregando"))
        self.comboBox_Status.setItemText(4, _translate("TelaPrincipal", "Finalizado"))
        self.pushButton_Enviar.setText(_translate("TelaPrincipal", "Enviar"))
